use spot_master_db;
INSERT INTO spot_master_db.images (id, image_path_1, image_path_2, description) VALUES (1, 'image_01.jpg', 'image_01_diff.jpg', 'Image 1');
INSERT INTO spot_master_db.images (id, image_path_1, image_path_2, description) VALUES (2, 'image_02.jpg', 'image_02_diff.jpg', 'Image 2');
INSERT INTO spot_master_db.images (id, image_path_1, image_path_2, description) VALUES (3, 'image_03.jpg', 'image_03_diff.jpg', 'Image 3');
INSERT INTO spot_master_db.images (id, image_path_1, image_path_2, description) VALUES (4, 'image_04.jpg', 'image_04_diff.jpg', 'Image 4');
INSERT INTO spot_master_db.images (id, image_path_1, image_path_2, description) VALUES (5, 'image_05.jpg', 'image_05_diff.jpg', 'Image 5');

INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (1, 1, 75, 338);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (2, 1, 16, 141);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (3, 1, 159, 208);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (4, 1, 221, 248);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (5, 1, 377, 352);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (6, 2, 183, 261);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (7, 2, 153, 338);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (8, 2, 35, 163);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (9, 2, 189, 118);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (10, 2, 480, 137);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (11, 3, 44, 309);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (12, 3, 253, 322);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (13, 3, 210, 268);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (14, 3, 360, 111);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (15, 3, 485, 227);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (16, 4, 77, 285);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (17, 4, 366, 167);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (18, 4, 153, 151);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (19, 4, 190, 75);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (20, 4, 380, 80);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (21, 5, 160, 129);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (22, 5, 58, 322);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (23, 5, 255, 345);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (24, 5, 311, 167);
INSERT INTO spot_master_db.differences (id, image_id, x_coordinate, y_coordinate) VALUES (25, 5, 364, 207);
